import { StyleSheet } from "react-native";

const menuStyles = StyleSheet.create({
  container: {
    flex: 1,
    position: "relative",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "f5fffa",
  },
  hero: {
    position: "relative",
    width: "100%",
    height: 475,
    zIndex: 80,
    marginBottom: 50,
  },
  heroBtn: {
    position: "relative",
    width: "100%",
    height: "100%",
  },
  heroTitle1: {
    fontFamily: "Poppins_700Bold",
    fontSize: 100,
    color: "#1210af",
    position: "absolute",
    left: 50,
    top: 0,
    zIndex: 2,
  },
  heroTitle2: {
    fontFamily: "Poppins_700Bold",
    fontSize: 100,
    color: "#1210af",
    position: "absolute",
    left: 70,
    top: 120,
    zIndex: 2,
  },
  heroText: {
    fontFamily: "Poppins_400Regular",
    fontSize: 30,
    color: "#1210af",
    zIndex: 1,
    position: "absolute",
    width: 500,
    display: "flex",
    flexWrap: "wrap",
    top: 280,
    textAlign: "center",
    left: 60,
  },
  heroBanner: {
    position: "absolute",
    width: 900,
    top: -98,
    left: 40,
    zIndex: 0,
  },
  heroPerson: {
    position: "absolute",
    width: 500,
    top: -50,
    left: 440,
    zIndex: 0,
  },
  footer: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
    height: 510,
  },
  footer1: {
    position: "relative",
    width: "50%",
    height: 510,
  },
  footer2: {
    position: "relative",
    width: "50%",
    height: 510,
  },
  footerBtn1: {
    position: "relative",
    width: "100%",
    height: 510,
  },
  footerBtn2: {
    position: "relative",
    width: "100%",
    height: 510,
  },
  interShape: {
    position: "absolute",
    width: 400,
    top: -156,
    left: 40,
    zIndex: 0,
  },
  questionsShape: {
    position: "absolute",
    width: 400,
    top: -50,
    left: 40,
    zIndex: 0,
  },
  interTitle1: {
    fontFamily: "Poppins_700Bold",
    fontSize: 70,
    color: "#1210af",
    position: "absolute",
    left: 50,
    top: 20,
    zIndex: 2,
  },
  interTitle2: {
    fontFamily: "Poppins_700Bold",
    fontSize: 65,
    color: "#1210af",
    position: "absolute",
    left: 50,
    top: 110,
    zIndex: 2,
  },
  interPerson: {
    position: "absolute",
    width: 250,
    top: -270,
    left: 220,
    zIndex: 0,
  },
  footerText1: {
    fontFamily: "Poppins_400Regular",
    fontSize: 25,
    color: "#1210af",
    zIndex: 1,
    position: "absolute",
    width: 220,
    display: "flex",
    flexWrap: "wrap",
    top: 210,
    textAlign: "center",
    left: 40,
  },
  footerText2: {
    fontFamily: "Poppins_400Regular",
    fontSize: 25,
    color: "#1210af",
    zIndex: 1,
    position: "absolute",
    width: 220,
    display: "flex",
    flexWrap: "wrap",
    top: 210,
    textAlign: "center",
    left: 40,
  },
  person1: {
    position: "absolute",
    width: 150,
    top: -190,
    left: -30,
    zIndex: 1,
  },
  person2: {
    position: "absolute",
    width: 150,
    top: -190,
    left: 300,
    zIndex: 1,
  },
  questionsText: {
    fontFamily: "Poppins_400Regular",
    fontSize: 25,
    color: "#1210af",
    zIndex: 1,
    position: "absolute",
    width: 220,
    display: "flex",
    flexWrap: "wrap",
    top: 210,
    textAlign: "center",
    left: 100,
  },
  questionsTitle1: {
    fontFamily: "Poppins_700Bold",
    fontSize: 70,
    width: 400,
    color: "#1210af",
    position: "absolute",
    left: 80,
    top: 20,
    zIndex: 2,
  },
  questionsTitle2: {
    fontFamily: "Poppins_700Bold",
    fontSize: 65,
    width: 410,
    color: "#1210af",
    position: "absolute",
    left: 50,
    top: 100,
    zIndex: 2,
  },
});

export default menuStyles;
